# listen_addr = ":3000"
data_dir = "./work"
library_dir = "/Some/Path"
username = "admin" # Username of the first user
initial_password = "admin" # Initial Password for user (should change after first login)
jwt_secret = "" # Example: openssl rand -base64 32
