// THIS FILE IS GENERATED BY PYRIN GOGEN CODE GENERATOR
package api

type Serie struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type GetSeries struct {
	Series []Serie `json:"series"`
}

type Bookmark struct {
	ChapterId string `json:"chapterId"`
}

type SerieUserData struct {
	Bookmark *Bookmark `json:"bookmark,omitempty"`
}

type GetSerieById struct {
	Id string `json:"id"`
	Name string `json:"name"`
	User *SerieUserData `json:"user,omitempty"`
}

type Chapter struct {
	Id string `json:"id"`
	Name string `json:"name"`
	SerieId string `json:"serieId"`
	Pages []string `json:"pages"`
	Number int `json:"number"`
	CoverArt string `json:"coverArt"`
}

type GetSerieChapters struct {
	Chapters []Chapter `json:"chapters"`
}

type GetChapters struct {
	Chapters []Chapter `json:"chapters"`
}

type GetChapterById struct {
	Id string `json:"id"`
	Name string `json:"name"`
	SerieId string `json:"serieId"`
	Pages []string `json:"pages"`
	Number int `json:"number"`
	CoverArt string `json:"coverArt"`
	NextChapter *string `json:"nextChapter,omitempty"`
	PrevChapter *string `json:"prevChapter,omitempty"`
}

type PostUserMarkChaptersBody struct {
	Chapters []string `json:"chapters"`
}

type PostUserUnmarkChaptersBody struct {
	Chapters []string `json:"chapters"`
}

type PostUserUpdateBookmarkBody struct {
	SerieId string `json:"serieId"`
	ChapterId string `json:"chapterId"`
	Page int `json:"page"`
}

type GetSystemInfo struct {
	Version string `json:"version"`
}

type Signup struct {
	Id string `json:"id"`
	Username string `json:"username"`
}

type SignupBody struct {
	Username string `json:"username"`
	Password string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type Signin struct {
	Token string `json:"token"`
}

type SigninBody struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type ChangePasswordBody struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword string `json:"newPassword"`
	NewPasswordConfirm string `json:"newPasswordConfirm"`
}

type GetMe struct {
	Id string `json:"id"`
	Username string `json:"username"`
	Role string `json:"role"`
	DisplayName string `json:"displayName"`
	QuickPlaylist *string `json:"quickPlaylist,omitempty"`
}

