// THIS FILE IS GENERATED BY PYRIN GOGEN CODE GENERATOR
package types

type Serie struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Cover        string `json:"cover"`
	ChapterCount int    `json:"chapterCount"`
}

type Chapter struct {
	SerieId string `json:"serieId"`
	Number  int    `json:"number"`
	Title   string `json:"title"`
}

type ChapterUserData struct {
	IsMarked bool `json:"isMarked"`
}

type GetSeries struct {
	Series []Serie `json:"series"`
}

type GetSerieById Serie

type GetSerieChaptersById struct {
	Chapters []Chapter `json:"chapters"`
}

type GetChapters struct {
	Chapters []Chapter `json:"chapters"`
}

type GetChapterById struct {
	SerieId     string           `json:"serieId"`
	Number      int              `json:"number"`
	Title       string           `json:"title"`
	NextChapter *int             `json:"nextChapter,omitempty"`
	PrevChapter *int             `json:"prevChapter,omitempty"`
	Pages       []string         `json:"pages"`
	User        *ChapterUserData `json:"user,omitempty"`
}
